# Generated by Django 5.1.4 on 2025-01-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
