# Generated by Django 5.1.4 on 2025-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0002_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_photo', models.ImageField(upload_to='static/FinanceApp/')),
                ('customer_pan_card', models.ImageField(upload_to='static/FinanceApp/')),
                ('customer_adhar', models.ImageField(upload_to='static/FinanceApp/')),
                ('customer_signature', models.ImageField(upload_to='static/FinanceApp/')),
                ('customer_address', models.TextField()),
                ('interest', models.CharField(max_length=100)),
                ('request_amount', models.CharField(max_length=100)),
                ('month_installation', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
