# Generated by Django 5.1.4 on 2025-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0004_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
