# Generated by Django 5.1.4 on 2025-01-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_contact_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('request_amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('month_installation', models.IntegerField()),
                ('month_installment', models.IntegerField()),
                ('acount_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('acount_no', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('action', models.DateTimeField()),
            ],
        ),
    ]
