# Generated by Django 5.1.4 on 2025-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0006_disbursed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursed',
            name='action',
            field=models.TextField(),
        ),
    ]
