# Generated by Django 5.1.4 on 2025-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0007_alter_disbursed_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursed',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
