# Generated by Django 5.1.4 on 2025-01-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0008_alter_disbursed_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursed',
            name='month_installment',
            field=models.FloatField(),
        ),
    ]
