# Generated by Django 5.1.4 on 2025-01-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_alter_disbursed_month_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customer_adhar',
            field=models.ImageField(upload_to='static/FinanceApp/media/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer_pan_card',
            field=models.ImageField(upload_to='static/FinanceApp/media/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer_photo',
            field=models.ImageField(upload_to='static/FinanceApp/media/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer_signature',
            field=models.ImageField(upload_to='static/FinanceApp/media/'),
        ),
    ]
