# Generated by Django 5.1.4 on 2025-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0012_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='adhar_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='pan_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer_mobile',
            field=models.CharField(max_length=15),
        ),
    ]
