# Generated by Django 5.1.4 on 2025-07-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0013_loan_adhar_number_loan_pan_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
