# Generated by Django 5.1.4 on 2025-07-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0014_delete_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursed',
            old_name='acount_holder_name',
            new_name='account_holder_name',
        ),
        migrations.RenameField(
            model_name='disbursed',
            old_name='acount_no',
            new_name='account_no',
        ),
        migrations.RemoveField(
            model_name='disbursed',
            name='user_id',
        ),
        migrations.AddField(
            model_name='disbursed',
            name='loan',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='disbursed_loans', to='FinanceApp.loan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disbursed',
            name='action',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
