# Generated by Django 5.1.4 on 2025-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0015_rename_acount_holder_name_disbursed_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursed',
            name='user_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
