# Generated by Django 5.1.4 on 2025-07-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0016_disbursed_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursed',
            old_name='account_holder_name',
            new_name='acount_holder_name',
        ),
        migrations.RenameField(
            model_name='disbursed',
            old_name='account_no',
            new_name='acount_no',
        ),
    ]
