# Generated by Django 5.1.4 on 2025-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0019_emischedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emischedule',
            name='user_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
