# Generated by Django 5.1.4 on 2025-10-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0020_emischedule_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.loan')),
            ],
        ),
    ]
