# Generated by Django 5.1.4 on 2025-10-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0021_loanotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanOTP',
        ),
    ]
