# Generated by Django 5.1.4 on 2025-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0022_delete_loanotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
