# Generated by Django 5.1.4 on 2025-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0023_loan_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursed',
            name='interest',
            field=models.FloatField(),
        ),
    ]
