# Generated by Django 5.1.4 on 2025-10-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0024_alter_disbursed_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursed',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
